// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Please add `import "dotenv/config";` to your `prisma.config.ts` file, or use the Prisma CLI with Bun
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";

// Load Next-style envs for Prisma CLI
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

const url = process.env.DATABASE_URL;
if (!url) {
  throw new Error(
    "DATABASE_URL is missing. Add it to .env.local (preferred) or .env before running Prisma commands."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",

  datasource: {
     url: process.env.PRISMA_MIGRATE_DATABASE_URL ?? process.env.DATABASE_URL!,
    //  shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL!,
  },

  migrations: {
    seed: "node --loader ts-node/esm prisma/seed.ts",
  },
});

